import type { InterviewFormValues } from "../validations/interview.schema";

export const interviewTableData: InterviewFormValues[] = [
  {
    id: 1,
    candidateId: 1,
    interviewDate: "2026-05-28",
    interviewTime: "10:30",
    departments: "Operations",
    interviewType:"Managerial Round",
    interviewer: "Bhavin Patel",
    interviewMode: "Online",
    interviewRoundStatus: "Scheduled",
    remark: "React + TypeScript round",
  },
  {
    id: 2,
    candidateId: 2,
    interviewDate: "2026-05-29",
    interviewTime: "14:00",
    departments: "Information Technology",
    interviewType: "HR",
    interviewer: "Neha Sharma",
    interviewMode: "Offline",
    interviewRoundStatus: "Completed",
    remark: "Good communication skills",
  },
  {
    id: 3,
    candidateId: 3,
    interviewDate: "2026-05-30",
    interviewTime: "11:15",
    departments: "Administration",
    interviewType: "Techinal Round",
    interviewer: "Amit Verma",
    interviewMode: "Online",
    interviewRoundStatus: "Cancelled",
    remark: "Candidate unavailable",
  },
  {
    id: 4,
    candidateId: 3,
    interviewDate: "2026-05-01",
    interviewTime: "17:15",
    departments: "Administration",
    interviewType: "Techinal Round",
    interviewer: "Amit Verma",
    interviewMode: "Online",
    interviewRoundStatus: "Scheduled",
    remark: "Candidate unavailable",
  },
];
