import type { CandidateFormValues } from "../types/candidate.types";

export const CandidateTableData: CandidateFormValues[] = [
  {
    id: 1,
    firstName: "Bhavin",
    lastName: "Panchal",
    email: "bhavin@gmail.com",
    phone: "9876453627",
    experience: "1",
    skills: "React, TypeScript",
    currentCompany: "Techoma",
    status: "Created",
  },
  {
    id: 2,
    firstName: "Ram",
    lastName: "Charan",
    email: "ram@gmail.com",
    phone: "9876453628",
    experience: "2",
    skills: "Leadership, Strategy",
    currentCompany: "Techoma",
    status: "Hired",
  },
  {
    id: 3,
    firstName: "Vishal",
    lastName: "Patel",
    email: "vishal@gmail.com",
    phone: "9876453629",
    experience: "3",
    skills: "Next.js, Tailwind",
    currentCompany: "PeoplePulse",
    status: "Technical",
  },
  {
    id: 4,
    firstName: "Aarav",
    lastName: "Sharma",
    email: "aarav@gmail.com",
    phone: "9876453630",
    experience: "4",
    skills: "Node.js, MongoDB",
    currentCompany: "Infosys",
    status: "Shortlisted",
  },
  {
    id: 5,
    firstName: "Priya",
    lastName: "Mehta",
    email: "priya@gmail.com",
    phone: "9876453631",
    experience: "5",
    skills: "UI/UX, Figma",
    currentCompany: "TCS",
    status: "Rejected",
  },
  {
    id: 6,
    firstName: "Karan",
    lastName: "Joshi",
    email: "karan@gmail.com",
    phone: "9876453632",
    experience: "2",
    skills: "Python, Django",
    currentCompany: "Wipro",
    status: "Technical",
  },
  {
    id: 7,
    firstName: "Sneha",
    lastName: "Rao",
    email: "sneha@gmail.com",
    phone: "9876453633",
    experience: "6",
    skills: "HR Operations",
    currentCompany: "Accenture",
    status: "Hired",
  },
  {
    id: 8,
    firstName: "Aditya",
    lastName: "Verma",
    email: "aditya@gmail.com",
    phone: "9876453634",
    experience: "1",
    skills: "JavaScript, HTML, CSS",
    currentCompany: "Cognizant",
    status: "Created",
  },
];
